name: "GitHub Actions job_id parser"
description: "Greet someone and record the time"
inputs:
  github_token:
    description: "GITHUB_TOKEN to use GitHub API v3"
    required: true
  repository:
    description: "target GitHub repository"
    required: false
  run_id:
    description: "run_id of target workflow run"
    required: false
  job_name:
    description: "job_name of tartget workflow jobs"
    required: true
outputs:
  job_id:
    description: "job_id of target workflow jobs"
  html_url:
    description: "html_url of target workflow jobs"
runs:
  using: "docker"
  image: "Dockerfile"
