style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/Tiryoh/gha-jobid-action
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - refactor
        - chore
        - ci
        - docs
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      refactor: Refactoring
      ci: CI
      docs: Documentation Update
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE