name: Multi jobs Workflow
on:
  pull_request:
  workflow_dispatch:

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number: [ 1 ]
    steps:
    - run: |
        echo "job number: ${{ matrix.number }}"
